workflows:
  test-staging:
    name: Staging
        scripts:
            - name: Install npm dependencies
              script: |
                yarn install
            - name: Yarn Test
              script: |
                yarn jest
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods


