workflows:
  test-staging:
    name: Staging
    environment:
      ndk: r23
    scripts:
        - name: Hello World
          script: |
            - echo "Hello World!"
        - name: yarn install
          script: |
            - yarn
        - name: yarn testing
          script: |
            - yarn jest
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods

